---
resources:
  - name: hello-code
    type: git
    source:
      uri: git@github.com:holmes89/hello-example.git
      branch: main
      private_key: ((github.private-key)) #NOT NEEDED FOR THIS EXAMPLE
  - name: gh-release
    type: github-release
    source:
      owner: holmes89
      repository: hello-example
      access_token: ((github.access-token))

jobs:
- name: build
  plan:
  - get: hello-code
    trigger: true
  - task: build
    config:
      platform: linux
      inputs:
        - name: hello-code
          path: /hello-example
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/sh
        args:
          - -c
          - |
            cd hello-example
            go get ./...
            echo "Hello API" > name.txt
            echo "$(git rev-parse --short HEAD)" > tag.txt
            GOOS=linux GOARCH=amd64 go build -o hello_linux_amd64
            GOOS=linux GOARCH=arm64 go build -o hello_linux_arm64
  - put: gh-release
    params:
      name: hello-example/name.txt
      tag: hello-example/tag.txt
      globs:
        - hello-example/hello_linux_amd64
        - hello-example/hello_linux-arm64
