---
resources:
  - name: hello-code
    type: git
    source:
      uri: git@github.com:holmes89/hello-example.git
      branch: main
      private_key: ((github.private-key)) #NOT NEEDED FOR THIS EXAMPLE
  - name: gh-release
    type: github-release
    source:
      owner: holmes89
      repository: hello-example
      access_token: ((github.access-token))

jobs:
- name: lint
  plan:
  - get: hello-code
    trigger: true
  - task: run-lint
    config:
      caches:
        - path: gopath/
      platform: linux
      inputs:
        - name: hello-code
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/sh
        args: 
          - ./hello-code/ci/lint.sh
- name: test
  plan:
  - get: hello-code
    trigger: true
    passed: [lint]
  - task: run-test
    config:
      caches:
        - path: gopath/
      platform: linux
      inputs:
        - name: hello-code
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/sh
        args: 
          - ./hello-code/ci/test.sh
- name: build-binary
  plan:
  - get: hello-code
    trigger: true
    passed: [test]
  - task: build
    config:
      caches:
        - path: gopath/
      platform: linux
      inputs:
        - name: hello-code
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/sh
        args:
          - -c
          - |
            echo "Hello API" > ./meta/name.txt
            cd hello-code
            echo "$(git rev-parse --short HEAD)" > ../meta/tag.txt
            go get ./...
            GOOS=linux GOARCH=amd64 go build -o ../dist/hello_linux_amd64 cmd/server/main.go
            GOOS=linux GOARCH=arm64 go build -o ../dist/hello_linux_arm64 cmd/server/main.go
      outputs:
        - name: dist
        - name: meta
  - put: gh-release
    params:
      name: meta/name.txt
      tag: meta/tag.txt
      globs:
        - dist/*
- name: deploy-amd64-server
  plan:
    - get: gh-release
      passed: [build-binary]
      trigger: true
    - get: hello-code
    - task: pack-amd64 
      config:
        platform: linux
        params:
          AWS_ACCESS_KEY_ID: ((aws.access-key)) 
          AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
          BUILD_TYPE: amd64
          INSTANCE_TYPE: t3.nano
          AMI: ami-0a91cd140a1fc148a
        inputs:
          - name: hello-code
          - name: gh-release
        outputs:
          - name: packer-manifest-amd64
        image_resource:
          type: registry-image
          source: { repository: hashicorp/packer, tag: light }
        run:
          path: /bin/sh
          args:
            - ./hello-code/ci/packer-build.sh
    - task: deploy-amd64
      config:
        platform: linux
        params:
          AWS_ACCESS_KEY_ID: ((aws.access-key)) 
          AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
          BUILD_TYPE: amd64
        inputs:
          - name: hello-code
          - name: packer-manifest-amd64
        image_resource:
          type: registry-image
          source: { repository: hashicorp/terraform, tag: light }
        run:
          path: /bin/sh
          args:
            - ./hello-code/ci/terraform-deploy-server.sh      
- name: deploy-arm64-server
  plan:
    - get: gh-release
      passed: [build-binary]
      trigger: true
    - get: hello-code
    - task: pack-arm64 
      config:
        platform: linux
        params:
          AWS_ACCESS_KEY_ID: ((aws.access-key)) 
          AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
          BUILD_TYPE: arm64
          INSTANCE_TYPE: t3a.nano
          AMI: ami-0742a572c2ce45ebf
        inputs:
          - name: hello-code
          - name: gh-release
        outputs:
          - name: packer-manifest-arm64
        image_resource:
          type: registry-image
          source: { repository: hashicorp/packer, tag: light }
        run:
          path: /bin/sh
          args:
            - ./hello-code/ci/packer-build.sh
    - task: deploy-arm64
      config:
        platform: linux
        params:
          AWS_ACCESS_KEY_ID: ((aws.access-key)) 
          AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
          BUILD_TYPE: arm64
        inputs:
          - name: hello-code
          - name: packer-manifest-arm64
        image_resource:
          type: registry-image
          source: { repository: hashicorp/terraform, tag: light }
        run:
          path: /bin/sh
          args:
            - ./hello-code/ci/terraform-deploy-server.sh
